#
# AzuraCast Docker Compose Configuration File
#
# When updating, you will be prompted to replace this file with a new
# version; you should do this whenever possible to take advantage of
# new updates.
#
# If you need to customize this file, you can create a new file named:
#   docker-compose.override.yml
# with any changes you need to make.
#

name: azuracast

services:
  web:
    container_name: azuracast
    image: "ghcr.io/azuracast/azuracast:${AZURACAST_VERSION:-latest}"
    labels:
      - "com.centurylinklabs.watchtower.scope=azuracast"
      - traefik.enable=true

      # HTTPS router for azuracast.whiskeylaser.com
      - "traefik.http.routers.u40wg4kkckkk8kwok8g04k8c.rule=Host(`azuracast.whiskeylaser.com`) && PathPrefix(`/`)"
      - traefik.http.routers.u40wg4kkckkk8kwok8g04k8c.entryPoints=http
      - traefik.docker.network=coolify-proxy
      - traefik.http.services.u40wg4kkckkk8kwok8g04k8c.loadbalancer.server.port=6970
    environment:
      - AZURACAST_HTTP_PORT=6970
      - AZURACAST_HTTPS_PORT=6969
      - AZURACAST_SFTP_PORT=2022
    volumes:
      - station_data:/var/azuracast/stations
      - backups:/var/azuracast/backups
      - db_data:/var/lib/mysql
      - www_uploads:/var/azuracast/storage/uploads
      - shoutcast2_install:/var/azuracast/storage/shoutcast2
      - stereo_tool_install:/var/azuracast/storage/stereo_tool
      - rsas_install:/var/azuracast/storage/rsas
      - geolite_install:/var/azuracast/storage/geoip
      - sftpgo_data:/var/azuracast/storage/sftpgo
      - acme:/var/azuracast/storage/acme
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    logging:
      options:
        max-size: "1m"
        max-file: "5"
    networks:
      - coolify-proxy

  updater:
    container_name: azuracast_updater
    image: ghcr.io/azuracast/updater:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      options:
        max-size: "1m"
        max-file: "5"

volumes:
  db_data: { }
  acme: { }
  shoutcast2_install: { }
  stereo_tool_install: { }
  rsas_install: { }
  geolite_install: { }
  sftpgo_data: { }
  station_data: { }
  www_uploads: { }
  backups: { }
