version: '3.8'

services:
  azuracast-installer:
    container_name: azuracast_installer
    image: 'ghcr.io/azuracast/azuracast:${AZURACAST_VERSION:-latest}'
    volumes:
      - './:/installer'
    restart: 'no'
    entrypoint: docker_installer
    command: install
    privileged: true

  web:
    depends_on:
      azuracast-installer:
        condition: service_completed_successfully
    entrypoint: ["/bin/sh", "-c", "while [ ! -f /var/azuracast/.installed ]; do sleep 5; done && /init"]